name: Deploy
on:
  push: { branches: [main] }
  workflow_dispatch:
jobs:
  maysante-front:
    uses: nod3win/.github/.github/workflows/vpsctl-deploy.yml@main
    with: { app: maysante-front }
    secrets: inherit
